# Generated by Django 3.2.9 on 2021-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generator_text',
            field=models.TextField(default='Alo', verbose_name='generator_text'),
            preserve_default=False,
        ),
    ]
